name: general_ai_server
description: A Library Full Package Template
version: 0.0.0
homepage: https://github.com/azkadev/general_ai
repository: https://github.com/azkadev/general_ai
issue_tracker: https://github.com/azkadev/general_ai/issues 
documentation: https://youtube.com/@azkadev
funding:
  - https://github.com/sponsors/azkadev


platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:

# topics:
#   - general_ai
#   - general_ai_flutter
#   - general_ai_dart
environment:
  sdk: ^3.2.3

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
